---
- hosts: "{{ env }}"
  gather_facts: false

  roles:
    - name: Generator Configs from Templates Role
      role: generator_config

    - name: Load or Update configurations to Local
      role: k8s_uploader