spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  groovy:
    template:
      check-template-location: false

logbook:
  strategy: body-only-if-status-at-least
  format:
    style: http
  logger:
    name: GOOGLE-AUTH-REST
  exclude:
    - /actuator/*

outbound:
  feign:
    user-handler:
      host: "http://localhost:${OUTBOUND_FEIGN_USER_HANDLER_PORT}/google"