spring:
  security:
    qrcheck:
      api-key:
        token:
          outgoing: ${DEFAULT_API_KEY_OUTGOING}
      auth-server:
        host: ${outbound.feign.auth-handler.host}
      oauth2:
        enabled: false
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
            api:
              url: https://oauth2.googleapis.com
              token-info: /tokeninfo
              token-refresh: /token

  groovy:
    template:
      check-template-location: false

springdoc:
  api-docs:
    path: "/swagger-api"
    enabled: true
  swagger-ui:
    path: "/"
  info:
    title: Google Auth RESTful API
    description: Сервис управления oAuth2 для Google
    version: V1
    licence-url: https://qrchk.ru/licence
    owner-name: QRCheck
    owner-url: https://qrchk.ru
    owner-email: it.support@softdarom.ru

logbook:
  strategy: body-only-if-status-at-least
  format:
    style: http
  logger:
    name: GOOGLE-AUTH-REST
  exclude:
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-api/**

outbound:
  feign:
    auth-handler:
      host: "${AUTH_HANDLER_HOST}"