---
- name: Upload Configs
  k8s:
    state: present
    src: "{{ k8s.directory.configs }}/{{ item }}"
    validate:
      fail_on_error: yes
  with_items: "{{ k8s.files }}"
  when: upload is defined and upload in ['yes', 'true', 'y']