filebeat:
  name: filebeat
  index: "qrcheck-{{ env }}"
  port:
    tcp:
      name: tcp
      number: 5066
  path:
    input: /tmp/filebeat/input
    config: /usr/share/filebeat
  logstash:
    host: logstash-logstash.elk:5044

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 256Mi