---
- name: Create k8s config folder
  file:
    dest: "{{ k8s.directory.configs }}"
    state: directory

- name: Generate Kubernetes Configs from Templates
  template:
    src: "{{ k8s.directory.templates }}/{{ item }}.j2"
    dest: "{{ k8s.directory.configs }}/{{ item }}"
  with_items: "{{ k8s.files }}"